package controller;

public enum Events {
    INITIAL_PANEL_ACTIONS, ADD_PROCESS, EXIT, EXIT_DIALOG, EXIT_DIALOG_EXCEPTION, START_SIMULATION, EDIT_PROCESS, NEW_TRANSITION,
    CREATE_PROCESS, CREATE_PARTITION, ADD_CHANGES, ENTER_EDIT, ENTER_CREATE, BACK, CREATE_PARTITION_DIALOG,
    CREATE_PROCESS_DIALOG, EXIT_PROCESS, EXIT_PARTITION, DELETE_PROCESS, ENTER_DELETE, EXIT_DIALOG_EDIT,
    EXIT_DIALOG_DELETE;
}
